import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';

jest.mock('@/lib/react-query/useDebt', () => ({ useCountyPendingBills: () => ({ data: undefined }) }));
jest.mock('@/components/ModelledDataNote', () => ({ __esModule: true, default: () => null }));
import BudgetTab from '@/app/counties/[id]/tabs/BudgetTab';
import type { CountyComprehensive } from '@/types';

function account(outstanding: number | null, total: number | null): CountyComprehensive {
  return {
    id: '1', name: 'Synthetic County',
    budget: { total_allocated: 100, total_spent: 50, utilization_rate: 50 },
    debt: {
      total_debt: total, pending_bills: null,
      breakdown: [{ lender: 'Synthetic Bank', principal: 100, outstanding }],
    },
  } as CountyComprehensive;
}

test.each([[null, 100], [10, null], [0, 0]])('absent/undefined share renders absence for %s / %s', (outstanding, total) => {
  render(<BudgetTab data={account(outstanding, total)} />);
  expect(screen.queryByText(/^0\.0%.*of total debt/i)).not.toBeInTheDocument();
  expect(screen.getByText(/—.*of total debt/i)).toBeInTheDocument();
});

test.each([[0, '0.0%'], [20, '20.0%']])('reported outstanding %s keeps its supported share', (outstanding, share) => {
  render(<BudgetTab data={account(outstanding, 100)} />);
  expect(screen.getByText(new RegExp(share.replace('.', '\\.') + '.*of total debt', 'i'))).toBeInTheDocument();
  expect(screen.getByText(outstanding === 0 ? 'KES 0' : 'KES 20')).toBeInTheDocument();
});

// Optional integrated receipt: generated by actual PostgreSQL comprehensive HTTP.
const receiptDir = process.env.FINANCIAL_ABSENCE_HTTP_CAPTURE_DIR;
(receiptDir ? test : test.skip)('mounted reader consumes captured PostgreSQL HTTP absence and sourced-zero states', () => {
  const fs = require('fs');
  const cases = [
    ['KES_dated', null], ['KES_undated', '100.0%'], ['USD_dated', null],
  ] as const;
  for (const [name, expectedShare] of cases) {
    const data = JSON.parse(fs.readFileSync(`${receiptDir}/ROUND8_SESSION_4_HTTP_${name}.json`, 'utf8')) as CountyComprehensive;
    const view = render(<BudgetTab data={data} />);
    if (expectedShare) {
      expect(screen.getByText(new RegExp('^' + expectedShare.replace('.', '\\.') + '.*of total debt', 'i'))).toBeInTheDocument();
    } else {
      expect(screen.getByText(/—.*of total debt/i)).toBeInTheDocument();
      expect(screen.queryByText(/^0\.0%.*of total debt/i)).not.toBeInTheDocument();
    }
    view.unmount();
  }
});
