"""baseline: full schema from models.py

Revision ID: 21d0394c1d6b
Revises:
Create Date: 2026-08-29

Replaces the previous 15-revision chain, archived under
``alembic/versions_archive_pre_baseline/`` and preserved in git history.

WHY THIS EXISTS
---------------
The old chain could not build a database. Eight of the 31 tables in
``models.py`` were created by no migration at all -- debt_timeline,
economic_indicators, fiscal_summaries, gdp_data, pending_bills,
population_data, poverty_indices and revenue_by_source -- which are eight of
the eleven fact tables holding published figures. A fresh replay died at
revision 2 on a missing column and, once that was guarded, at revision 5 with
``relation "population_data" does not exist``.

Those tables existed in every real environment only because ``database.py``
calls ``Base.metadata.create_all()`` at startup, building everything in
``models.py`` before migrations ran. The chain had therefore never been
executed in its own order anywhere, and CI's run-migrations job was green
only because it targeted an already-populated database.

This revision is generated from ``models.py`` and creates all 31 tables, so
schema and migrations agree by construction.

APPLYING TO AN EXISTING ENVIRONMENT
-----------------------------------
Do NOT run ``upgrade`` on a database that already has the schema. Point it at
this revision instead, which changes only the alembic_version pointer::

    alembic stamp 21d0394c1d6b

Verify first that the live schema matches this file::

    alembic check        # expects "No new upgrade operations detected."
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21d0394c1d6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_actor_id'), 'admin_audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_id'), 'admin_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_target_id'), 'admin_audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_target_type'), 'admin_audit_log', ['target_type'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('default_locale', sa.String(length=10), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.create_table('fiscal_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_years_id'), 'fiscal_years', ['id'], unique=False)
    op.create_index(op.f('ix_fiscal_years_label'), 'fiscal_years', ['label'], unique=True)
    op.create_table('imf_weo_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=16), nullable=False),
    sa.Column('indicator', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('is_projection', sa.Boolean(), nullable=False),
    sa.Column('vintage', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'indicator', 'year', 'vintage', name='uq_imf_weo_country_indicator_year_vintage')
    )
    op.create_index('ix_imf_weo_country_indicator_year', 'imf_weo_observations', ['country_code', 'indicator', 'year'], unique=False)
    op.create_index(op.f('ix_imf_weo_observations_id'), 'imf_weo_observations', ['id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='ingestionstatus'), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_domain'), 'ingestion_jobs', ['domain'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_table('quick_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('BUDGET_BASICS', 'AUDIT_FUNDAMENTALS', 'DEBT_MANAGEMENT', 'FINANCIAL_TRANSPARENCY', 'GOVERNANCE', 'PUBLIC_FINANCE', name='questioncategory'), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_questions_id'), 'quick_questions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.create_table('data_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=30), nullable=True),
    sa.Column('item_id', sa.String(length=100), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_alerts_id'), 'data_alerts', ['id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('NATIONAL', 'COUNTY', 'MINISTRY', 'AGENCY', 'MUNICIPALITY', 'STATE_CORPORATION', 'JUDICIARY', 'COMMISSION', 'FUND', 'CONSTITUENCY', 'SUB_COUNTY', name='entitytype'), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('alt_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_slug'), 'entities', ['slug'], unique=True)
    op.create_table('fiscal_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'label', name='uq_fiscal_period_country_label')
    )
    op.create_index(op.f('ix_fiscal_periods_id'), 'fiscal_periods', ['id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('fetch_date', sa.DateTime(), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('doc_type', sa.Enum('BUDGET', 'AUDIT', 'REPORT', 'LOAN', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ARCHIVED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_id'), 'source_documents', ['id'], unique=False)
    op.create_table('user_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quick_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_question_answers_id'), 'user_question_answers', ['id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='uq_watchlist_user_type_item')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('finding_text', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('audit_opinion', sa.String(length=50), nullable=True),
    sa.Column('audit_year', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('management_response', sa.Text(), nullable=True),
    sa.Column('follow_up_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_entity_id'), 'audits', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_index(op.f('ix_audits_period_id'), 'audits', ['period_id'], unique=False)
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_spent', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('committed_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('page_ref', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'period_id', 'category', 'subcategory', name='uq_budget_entity_period_cat_subcat')
    )
    op.create_index(op.f('ix_budget_lines_entity_id'), 'budget_lines', ['entity_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_id'), 'budget_lines', ['id'], unique=False)
    op.create_index(op.f('ix_budget_lines_period_id'), 'budget_lines', ['period_id'], unique=False)
    op.create_table('constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('county_entity_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['county_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_constituency_name')
    )
    op.create_index(op.f('ix_constituencies_code'), 'constituencies', ['code'], unique=True)
    op.create_index(op.f('ix_constituencies_county_entity_id'), 'constituencies', ['county_entity_id'], unique=False)
    op.create_index(op.f('ix_constituencies_id'), 'constituencies', ['id'], unique=False)
    op.create_table('county_org_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'name', name='uq_county_org_entity_name')
    )
    op.create_index(op.f('ix_county_org_units_entity_id'), 'county_org_units', ['entity_id'], unique=False)
    op.create_index(op.f('ix_county_org_units_id'), 'county_org_units', ['id'], unique=False)
    op.create_table('debt_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('external', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('domestic', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gdp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gdp_ratio', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_timeline_id'), 'debt_timeline', ['id'], unique=False)
    op.create_index(op.f('ix_debt_timeline_year'), 'debt_timeline', ['year'], unique=True)
    op.create_table('economic_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('indicator_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_type', 'indicator_date', 'entity_id', name='uq_econ_type_date_entity')
    )
    op.create_index(op.f('ix_economic_indicators_id'), 'economic_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_economic_indicators_indicator_date'), 'economic_indicators', ['indicator_date'], unique=False)
    op.create_index(op.f('ix_economic_indicators_indicator_type'), 'economic_indicators', ['indicator_type'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extractor', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_id'), 'extractions', ['id'], unique=False)
    op.create_table('fiscal_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=20), nullable=False),
    sa.Column('appropriated_budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('non_tax_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_borrowing', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('borrowing_pct_of_budget', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('debt_service_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('debt_service_per_shilling', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('debt_ceiling', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('debt_ceiling_usage_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('development_spending', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recurrent_spending', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('county_allocation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_summaries_fiscal_year'), 'fiscal_summaries', ['fiscal_year'], unique=True)
    op.create_index(op.f('ix_fiscal_summaries_id'), 'fiscal_summaries', ['id'], unique=False)
    op.create_table('gdp_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=2), nullable=True),
    sa.Column('gdp_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('gdp_growth_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'year', 'quarter', name='uq_gdp_entity_year_quarter')
    )
    op.create_index(op.f('ix_gdp_data_entity_id'), 'gdp_data', ['entity_id'], unique=False)
    op.create_index(op.f('ix_gdp_data_id'), 'gdp_data', ['id'], unique=False)
    op.create_index(op.f('ix_gdp_data_quarter'), 'gdp_data', ['quarter'], unique=False)
    op.create_index(op.f('ix_gdp_data_year'), 'gdp_data', ['year'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('lender', sa.String(length=200), nullable=False),
    sa.Column('debt_category', sa.Enum('EXTERNAL_MULTILATERAL', 'EXTERNAL_BILATERAL', 'EXTERNAL_COMMERCIAL', 'DOMESTIC_BONDS', 'DOMESTIC_BILLS', 'DOMESTIC_OVERDRAFT', 'PENDING_BILLS', 'COUNTY_GUARANTEED', 'OTHER', name='debtcategory'), nullable=True),
    sa.Column('principal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'lender', 'issue_date', name='uq_loans_entity_lender_date')
    )
    op.create_index(op.f('ix_loans_debt_category'), 'loans', ['debt_category'], unique=False)
    op.create_index(op.f('ix_loans_entity_id'), 'loans', ['entity_id'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_table('national_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('parent_ministry_entity_id', sa.Integer(), nullable=True),
    sa.Column('establishment_act', sa.String(length=300), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['parent_ministry_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', name='uq_national_entity')
    )
    op.create_index(op.f('ix_national_entities_id'), 'national_entities', ['id'], unique=False)
    op.create_table('parliament_source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('dspace_uuid', sa.String(length=64), nullable=True),
    sa.Column('dspace_handle', sa.String(length=100), nullable=True),
    sa.Column('collection_uuid', sa.String(length=64), nullable=True),
    sa.Column('community_uuid', sa.String(length=64), nullable=True),
    sa.Column('parliament_doc_type', sa.Enum('audit_report', 'committee_report', 'budget_estimate', 'green_book', 'hansard', 'bill', 'act', 'policy_document', 'other', name='parliamentdoctype'), nullable=True),
    sa.Column('tabling_date', sa.DateTime(), nullable=True),
    sa.Column('fiscal_year_label', sa.String(length=20), nullable=True),
    sa.Column('committee_name', sa.String(length=200), nullable=True),
    sa.Column('entity_table', sa.String(length=50), nullable=True),
    sa.Column('entity_ref_id', sa.Integer(), nullable=True),
    sa.Column('audit_opinion', sa.Enum('unqualified', 'qualified', 'adverse', 'disclaimer', name='auditopinion'), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', name='uq_parliament_src_doc')
    )
    op.create_index(op.f('ix_parliament_source_documents_dspace_uuid'), 'parliament_source_documents', ['dspace_uuid'], unique=True)
    op.create_index(op.f('ix_parliament_source_documents_id'), 'parliament_source_documents', ['id'], unique=False)
    op.create_table('pending_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.Enum('SUPPLIER_ARREARS', 'SALARY', 'PENSION', 'STATUTORY', 'COURT_AWARDS', 'OTHER', name='billtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fiscal_year', sa.String(length=20), nullable=False),
    sa.Column('aging_days', sa.Integer(), nullable=True),
    sa.Column('eligible_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ineligible_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'bill_type', 'fiscal_year', name='uq_pending_bill_entity_type_fy')
    )
    op.create_index(op.f('ix_pending_bills_entity_id'), 'pending_bills', ['entity_id'], unique=False)
    op.create_index(op.f('ix_pending_bills_fiscal_year'), 'pending_bills', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_pending_bills_id'), 'pending_bills', ['id'], unique=False)
    op.create_table('population_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('male_population', sa.Integer(), nullable=True),
    sa.Column('female_population', sa.Integer(), nullable=True),
    sa.Column('urban_population', sa.Integer(), nullable=True),
    sa.Column('rural_population', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'year', name='uq_population_entity_year')
    )
    op.create_index(op.f('ix_population_data_entity_id'), 'population_data', ['entity_id'], unique=False)
    op.create_index(op.f('ix_population_data_id'), 'population_data', ['id'], unique=False)
    op.create_index(op.f('ix_population_data_year'), 'population_data', ['year'], unique=False)
    op.create_table('poverty_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('poverty_headcount_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extreme_poverty_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gini_coefficient', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'year', name='uq_poverty_entity_year')
    )
    op.create_index(op.f('ix_poverty_indices_id'), 'poverty_indices', ['id'], unique=False)
    op.create_index(op.f('ix_poverty_indices_year'), 'poverty_indices', ['year'], unique=False)
    op.create_table('revenue_by_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=20), nullable=False),
    sa.Column('revenue_type', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('amount_billion_kes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('target_billion_kes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('performance_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('share_of_total_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('yoy_growth_pct', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year', 'revenue_type', name='uq_revenue_fy_type')
    )
    op.create_index(op.f('ix_revenue_by_source_fiscal_year'), 'revenue_by_source', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_revenue_by_source_id'), 'revenue_by_source', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_by_source_revenue_type'), 'revenue_by_source', ['revenue_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_by_source_revenue_type'), table_name='revenue_by_source')
    op.drop_index(op.f('ix_revenue_by_source_id'), table_name='revenue_by_source')
    op.drop_index(op.f('ix_revenue_by_source_fiscal_year'), table_name='revenue_by_source')
    op.drop_table('revenue_by_source')
    op.drop_index(op.f('ix_poverty_indices_year'), table_name='poverty_indices')
    op.drop_index(op.f('ix_poverty_indices_id'), table_name='poverty_indices')
    op.drop_table('poverty_indices')
    op.drop_index(op.f('ix_population_data_year'), table_name='population_data')
    op.drop_index(op.f('ix_population_data_id'), table_name='population_data')
    op.drop_index(op.f('ix_population_data_entity_id'), table_name='population_data')
    op.drop_table('population_data')
    op.drop_index(op.f('ix_pending_bills_id'), table_name='pending_bills')
    op.drop_index(op.f('ix_pending_bills_fiscal_year'), table_name='pending_bills')
    op.drop_index(op.f('ix_pending_bills_entity_id'), table_name='pending_bills')
    op.drop_table('pending_bills')
    op.drop_index(op.f('ix_parliament_source_documents_id'), table_name='parliament_source_documents')
    op.drop_index(op.f('ix_parliament_source_documents_dspace_uuid'), table_name='parliament_source_documents')
    op.drop_table('parliament_source_documents')
    op.drop_index(op.f('ix_national_entities_id'), table_name='national_entities')
    op.drop_table('national_entities')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_entity_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_debt_category'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_gdp_data_year'), table_name='gdp_data')
    op.drop_index(op.f('ix_gdp_data_quarter'), table_name='gdp_data')
    op.drop_index(op.f('ix_gdp_data_id'), table_name='gdp_data')
    op.drop_index(op.f('ix_gdp_data_entity_id'), table_name='gdp_data')
    op.drop_table('gdp_data')
    op.drop_index(op.f('ix_fiscal_summaries_id'), table_name='fiscal_summaries')
    op.drop_index(op.f('ix_fiscal_summaries_fiscal_year'), table_name='fiscal_summaries')
    op.drop_table('fiscal_summaries')
    op.drop_index(op.f('ix_extractions_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_economic_indicators_indicator_type'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_indicator_date'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_id'), table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_index(op.f('ix_debt_timeline_year'), table_name='debt_timeline')
    op.drop_index(op.f('ix_debt_timeline_id'), table_name='debt_timeline')
    op.drop_table('debt_timeline')
    op.drop_index(op.f('ix_county_org_units_id'), table_name='county_org_units')
    op.drop_index(op.f('ix_county_org_units_entity_id'), table_name='county_org_units')
    op.drop_table('county_org_units')
    op.drop_index(op.f('ix_constituencies_id'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_county_entity_id'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_code'), table_name='constituencies')
    op.drop_table('constituencies')
    op.drop_index(op.f('ix_budget_lines_period_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_entity_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_audits_period_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_entity_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_user_question_answers_id'), table_name='user_question_answers')
    op.drop_table('user_question_answers')
    op.drop_index(op.f('ix_source_documents_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_fiscal_periods_id'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    op.drop_index(op.f('ix_entities_slug'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_data_alerts_id'), table_name='data_alerts')
    op.drop_table('data_alerts')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quick_questions_id'), table_name='quick_questions')
    op.drop_table('quick_questions')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_domain'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_imf_weo_observations_id'), table_name='imf_weo_observations')
    op.drop_index('ix_imf_weo_country_indicator_year', table_name='imf_weo_observations')
    op.drop_table('imf_weo_observations')
    op.drop_index(op.f('ix_fiscal_years_label'), table_name='fiscal_years')
    op.drop_index(op.f('ix_fiscal_years_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_admin_audit_log_target_type'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_target_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_actor_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###

    # Autogenerate creates these ENUM types implicitly with the tables that
    # use them, but does NOT drop them, so upgrade -> downgrade -> upgrade
    # failed with:
    #     DuplicateObject: type "ingestionstatus" already exists
    # Dropping them here is what makes the baseline genuinely reversible.
    for _enum in (
        "auditopinion",
        "billtype",
        "debtcategory",
        "documentstatus",
        "documenttype",
        "entitytype",
        "ingestionstatus",
        "parliamentdoctype",
        "questioncategory",
        "severity",
    ):
        op.execute(f'DROP TYPE IF EXISTS {_enum}')

