"""stage1: provenance and publication-gate columns

Revision ID: b3d8ab47bf3b
Revises: 21d0394c1d6b
Create Date: 2026-08-29 08:55:33.332037

PRODUCTION DRIFT, HANDLED HERE
------------------------------
Production (verified on a pg_dump clone, 2026-08-29) already has
``confidence_score numeric`` on ``audits`` and ``budget_lines`` — added
before the rebaseline, outside any surviving migration, and empty in both
tables (0/27 and 0/2059 non-null). A plain ``add_column`` therefore fails
with DuplicateColumn on production while succeeding on a fresh database.

Where the column pre-exists, this migration aligns its type to the model's
FLOAT (double precision) instead of adding it. The downgrade drops the
column either way, which on production removes a verified-empty column.

Production's ``entitytype`` enum also carries six labels added outside the
chain in LOWERCASE (``commission`` …) where the model — and a fresh replay
of this chain — use the enum member NAMES (``COMMISSION`` …). SQLAlchemy
sends the uppercase name, so inserting any of those entity types fails on
production today. No production row uses the lowercase labels (verified:
only COUNTY/MINISTRY/NATIONAL are in use), so they are renamed in place.
"""
import logging

from alembic import op
import sqlalchemy as sa


def _has_column(table: str, column: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return column in {c["name"] for c in inspector.get_columns(table)}


logger = logging.getLogger("alembic.stage1")


def _drop_confidence_score_only_if_we_added_it(table: str) -> None:
    """Never drop a ``confidence_score`` that PRE-DATES this migration.

    ``audits`` and ``budget_lines`` already had a ``confidence_score
    numeric(3,2)`` before Stage 1; the upgrade only widens it to float via
    :func:`_add_or_align_confidence_score`, and adds it outright on the
    eleven tables that lacked it. The autogenerated downgrade dropped it
    unconditionally on all thirteen, so a rollback DESTROYED two columns the
    migration never created.

    Caught on 2026-08-30 by rolling production back: the restored schema was
    two columns short of the snapshot taken minutes earlier
    (``audits.confidence_score``, ``budget_lines.confidence_score``). A
    downgrade that loses data the upgrade did not add is not a downgrade.

    There is no record of which side added it, so the safe direction is to
    leave these two alone: an over-wide column is harmless, a missing one is
    a runtime error. The other eleven tables still drop theirs, because on
    those the upgrade genuinely created it.
    """
    logger.info(
        "downgrade: leaving %s.confidence_score in place — it pre-dates this "
        "migration and dropping it would lose a column the upgrade never added",
        table,
    )


def _add_or_align_confidence_score(table: str) -> None:
    if _has_column(table, "confidence_score"):
        op.alter_column(
            table,
            "confidence_score",
            type_=sa.Float(),
            postgresql_using="confidence_score::double precision",
        )
    else:
        op.add_column(
            table, sa.Column("confidence_score", sa.Float(), nullable=True)
        )


# revision identifiers, used by Alembic.
revision = 'b3d8ab47bf3b'
down_revision = '21d0394c1d6b'
branch_labels = None
depends_on = None


def _normalize_entitytype_labels() -> None:
    bind = op.get_bind()
    labels = {
        row[0]
        for row in bind.execute(
            sa.text(
                "select e.enumlabel from pg_enum e "
                "join pg_type t on t.oid = e.enumtypid "
                "where t.typname = 'entitytype'"
            )
        )
    }
    for lower in (
        "state_corporation",
        "judiciary",
        "commission",
        "fund",
        "constituency",
        "sub_county",
    ):
        upper = lower.upper()
        if lower in labels and upper not in labels:
            bind.execute(
                sa.text(
                    f"ALTER TYPE entitytype RENAME VALUE '{lower}' TO '{upper}'"
                )
            )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _normalize_entitytype_labels()
    # PostgreSQL needs the ENUM type to exist before a column can use it.
    # `op.add_column` with sa.Enum does NOT create it, so a fresh upgrade died
    # with: UndefinedObject: type "figurebasis" does not exist
    figurebasis = sa.Enum("ACTUAL", "MODELLED", "PROJECTED", name="figurebasis")
    figurebasis.create(op.get_bind(), checkfirst=True)

    op.add_column('audits', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('audits', sa.Column('source_hash', sa.String(length=64), nullable=True))
    _add_or_align_confidence_score('audits')
    op.add_column('audits', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('audits', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('audits', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_audits_basis'), 'audits', ['basis'], unique=False)
    op.create_index(op.f('ix_audits_extraction_id'), 'audits', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_audits_publishable'), 'audits', ['publishable'], unique=False)
    op.create_foreign_key('fk_audits_extraction_id_extractions', 'audits', 'extractions', ['extraction_id'], ['id'])
    op.add_column('budget_lines', sa.Column('line_type', sa.String(length=20), nullable=True))
    op.add_column('budget_lines', sa.Column('extraction_id', sa.Integer(), nullable=True))
    _add_or_align_confidence_score('budget_lines')
    op.add_column('budget_lines', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('budget_lines', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('budget_lines', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_budget_lines_basis'), 'budget_lines', ['basis'], unique=False)
    op.create_index(op.f('ix_budget_lines_extraction_id'), 'budget_lines', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_line_type'), 'budget_lines', ['line_type'], unique=False)
    op.create_index(op.f('ix_budget_lines_publishable'), 'budget_lines', ['publishable'], unique=False)
    op.create_foreign_key('fk_budget_lines_extraction_id_extractions', 'budget_lines', 'extractions', ['extraction_id'], ['id'])
    op.add_column('debt_timeline', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('debt_timeline', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('debt_timeline', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('debt_timeline', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('debt_timeline', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('debt_timeline', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('debt_timeline', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_debt_timeline_basis'), 'debt_timeline', ['basis'], unique=False)
    op.create_index(op.f('ix_debt_timeline_extraction_id'), 'debt_timeline', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_debt_timeline_publishable'), 'debt_timeline', ['publishable'], unique=False)
    op.create_foreign_key('fk_debt_timeline_extraction_id_extractions', 'debt_timeline', 'extractions', ['extraction_id'], ['id'])
    op.add_column('economic_indicators', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('economic_indicators', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('economic_indicators', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('economic_indicators', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('economic_indicators', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('economic_indicators', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('economic_indicators', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_economic_indicators_basis'), 'economic_indicators', ['basis'], unique=False)
    op.create_index(op.f('ix_economic_indicators_extraction_id'), 'economic_indicators', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_economic_indicators_publishable'), 'economic_indicators', ['publishable'], unique=False)
    op.create_foreign_key('fk_economic_indicators_extraction_id_extractions', 'economic_indicators', 'extractions', ['extraction_id'], ['id'])
    op.add_column('fiscal_summaries', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('fiscal_summaries', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('fiscal_summaries', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('fiscal_summaries', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('fiscal_summaries', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('fiscal_summaries', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('fiscal_summaries', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_fiscal_summaries_basis'), 'fiscal_summaries', ['basis'], unique=False)
    op.create_index(op.f('ix_fiscal_summaries_extraction_id'), 'fiscal_summaries', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_fiscal_summaries_publishable'), 'fiscal_summaries', ['publishable'], unique=False)
    op.create_foreign_key('fk_fiscal_summaries_extraction_id_extractions', 'fiscal_summaries', 'extractions', ['extraction_id'], ['id'])
    op.add_column('gdp_data', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('gdp_data', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('gdp_data', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('gdp_data', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('gdp_data', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('gdp_data', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('gdp_data', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_gdp_data_basis'), 'gdp_data', ['basis'], unique=False)
    op.create_index(op.f('ix_gdp_data_extraction_id'), 'gdp_data', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_gdp_data_publishable'), 'gdp_data', ['publishable'], unique=False)
    op.create_foreign_key('fk_gdp_data_extraction_id_extractions', 'gdp_data', 'extractions', ['extraction_id'], ['id'])
    op.add_column('loans', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('loans', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('loans', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('loans', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('loans', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_loans_basis'), 'loans', ['basis'], unique=False)
    op.create_index(op.f('ix_loans_extraction_id'), 'loans', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_loans_publishable'), 'loans', ['publishable'], unique=False)
    op.create_foreign_key('fk_loans_extraction_id_extractions', 'loans', 'extractions', ['extraction_id'], ['id'])
    op.add_column('pending_bills', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('pending_bills', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('pending_bills', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('pending_bills', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('pending_bills', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('pending_bills', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pending_bills', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_pending_bills_basis'), 'pending_bills', ['basis'], unique=False)
    op.create_index(op.f('ix_pending_bills_extraction_id'), 'pending_bills', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_pending_bills_publishable'), 'pending_bills', ['publishable'], unique=False)
    op.create_foreign_key('fk_pending_bills_extraction_id_extractions', 'pending_bills', 'extractions', ['extraction_id'], ['id'])
    op.add_column('population_data', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('population_data', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('population_data', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('population_data', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('population_data', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('population_data', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('population_data', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_population_data_basis'), 'population_data', ['basis'], unique=False)
    op.create_index(op.f('ix_population_data_extraction_id'), 'population_data', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_population_data_publishable'), 'population_data', ['publishable'], unique=False)
    op.create_foreign_key('fk_population_data_extraction_id_extractions', 'population_data', 'extractions', ['extraction_id'], ['id'])
    op.add_column('poverty_indices', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('poverty_indices', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('poverty_indices', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('poverty_indices', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('poverty_indices', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('poverty_indices', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('poverty_indices', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_poverty_indices_basis'), 'poverty_indices', ['basis'], unique=False)
    op.create_index(op.f('ix_poverty_indices_extraction_id'), 'poverty_indices', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_poverty_indices_publishable'), 'poverty_indices', ['publishable'], unique=False)
    op.create_foreign_key('fk_poverty_indices_extraction_id_extractions', 'poverty_indices', 'extractions', ['extraction_id'], ['id'])
    op.add_column('revenue_by_source', sa.Column('extraction_id', sa.Integer(), nullable=True))
    op.add_column('revenue_by_source', sa.Column('page_ref', sa.String(length=50), nullable=True))
    op.add_column('revenue_by_source', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('revenue_by_source', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('revenue_by_source', sa.Column('basis', sa.Enum('ACTUAL', 'MODELLED', 'PROJECTED', name='figurebasis', create_type=False), nullable=True))
    op.add_column('revenue_by_source', sa.Column('publishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('revenue_by_source', sa.Column('quarantine_reason', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_revenue_by_source_basis'), 'revenue_by_source', ['basis'], unique=False)
    op.create_index(op.f('ix_revenue_by_source_extraction_id'), 'revenue_by_source', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_revenue_by_source_publishable'), 'revenue_by_source', ['publishable'], unique=False)
    op.create_foreign_key('fk_revenue_by_source_extraction_id_extractions', 'revenue_by_source', 'extractions', ['extraction_id'], ['id'])
    op.add_column('source_documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('source_documents', sa.Column('http_status', sa.Integer(), nullable=True))
    op.add_column('source_documents', sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'last_verified_at')
    op.drop_column('source_documents', 'http_status')
    op.drop_column('source_documents', 'content_type')
    op.drop_constraint('fk_revenue_by_source_extraction_id_extractions', 'revenue_by_source', type_='foreignkey')
    op.drop_index(op.f('ix_revenue_by_source_publishable'), table_name='revenue_by_source')
    op.drop_index(op.f('ix_revenue_by_source_extraction_id'), table_name='revenue_by_source')
    op.drop_index(op.f('ix_revenue_by_source_basis'), table_name='revenue_by_source')
    op.drop_column('revenue_by_source', 'quarantine_reason')
    op.drop_column('revenue_by_source', 'publishable')
    op.drop_column('revenue_by_source', 'basis')
    op.drop_column('revenue_by_source', 'confidence_score')
    op.drop_column('revenue_by_source', 'source_hash')
    op.drop_column('revenue_by_source', 'page_ref')
    op.drop_column('revenue_by_source', 'extraction_id')
    op.drop_constraint('fk_poverty_indices_extraction_id_extractions', 'poverty_indices', type_='foreignkey')
    op.drop_index(op.f('ix_poverty_indices_publishable'), table_name='poverty_indices')
    op.drop_index(op.f('ix_poverty_indices_extraction_id'), table_name='poverty_indices')
    op.drop_index(op.f('ix_poverty_indices_basis'), table_name='poverty_indices')
    op.drop_column('poverty_indices', 'quarantine_reason')
    op.drop_column('poverty_indices', 'publishable')
    op.drop_column('poverty_indices', 'basis')
    op.drop_column('poverty_indices', 'confidence_score')
    op.drop_column('poverty_indices', 'source_hash')
    op.drop_column('poverty_indices', 'page_ref')
    op.drop_column('poverty_indices', 'extraction_id')
    op.drop_constraint('fk_population_data_extraction_id_extractions', 'population_data', type_='foreignkey')
    op.drop_index(op.f('ix_population_data_publishable'), table_name='population_data')
    op.drop_index(op.f('ix_population_data_extraction_id'), table_name='population_data')
    op.drop_index(op.f('ix_population_data_basis'), table_name='population_data')
    op.drop_column('population_data', 'quarantine_reason')
    op.drop_column('population_data', 'publishable')
    op.drop_column('population_data', 'basis')
    op.drop_column('population_data', 'confidence_score')
    op.drop_column('population_data', 'source_hash')
    op.drop_column('population_data', 'page_ref')
    op.drop_column('population_data', 'extraction_id')
    op.drop_constraint('fk_pending_bills_extraction_id_extractions', 'pending_bills', type_='foreignkey')
    op.drop_index(op.f('ix_pending_bills_publishable'), table_name='pending_bills')
    op.drop_index(op.f('ix_pending_bills_extraction_id'), table_name='pending_bills')
    op.drop_index(op.f('ix_pending_bills_basis'), table_name='pending_bills')
    op.drop_column('pending_bills', 'quarantine_reason')
    op.drop_column('pending_bills', 'publishable')
    op.drop_column('pending_bills', 'basis')
    op.drop_column('pending_bills', 'confidence_score')
    op.drop_column('pending_bills', 'source_hash')
    op.drop_column('pending_bills', 'page_ref')
    op.drop_column('pending_bills', 'extraction_id')
    op.drop_constraint('fk_loans_extraction_id_extractions', 'loans', type_='foreignkey')
    op.drop_index(op.f('ix_loans_publishable'), table_name='loans')
    op.drop_index(op.f('ix_loans_extraction_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_basis'), table_name='loans')
    op.drop_column('loans', 'quarantine_reason')
    op.drop_column('loans', 'publishable')
    op.drop_column('loans', 'basis')
    op.drop_column('loans', 'confidence_score')
    op.drop_column('loans', 'source_hash')
    op.drop_column('loans', 'page_ref')
    op.drop_column('loans', 'extraction_id')
    op.drop_constraint('fk_gdp_data_extraction_id_extractions', 'gdp_data', type_='foreignkey')
    op.drop_index(op.f('ix_gdp_data_publishable'), table_name='gdp_data')
    op.drop_index(op.f('ix_gdp_data_extraction_id'), table_name='gdp_data')
    op.drop_index(op.f('ix_gdp_data_basis'), table_name='gdp_data')
    op.drop_column('gdp_data', 'quarantine_reason')
    op.drop_column('gdp_data', 'publishable')
    op.drop_column('gdp_data', 'basis')
    op.drop_column('gdp_data', 'confidence_score')
    op.drop_column('gdp_data', 'source_hash')
    op.drop_column('gdp_data', 'page_ref')
    op.drop_column('gdp_data', 'extraction_id')
    op.drop_constraint('fk_fiscal_summaries_extraction_id_extractions', 'fiscal_summaries', type_='foreignkey')
    op.drop_index(op.f('ix_fiscal_summaries_publishable'), table_name='fiscal_summaries')
    op.drop_index(op.f('ix_fiscal_summaries_extraction_id'), table_name='fiscal_summaries')
    op.drop_index(op.f('ix_fiscal_summaries_basis'), table_name='fiscal_summaries')
    op.drop_column('fiscal_summaries', 'quarantine_reason')
    op.drop_column('fiscal_summaries', 'publishable')
    op.drop_column('fiscal_summaries', 'basis')
    op.drop_column('fiscal_summaries', 'confidence_score')
    op.drop_column('fiscal_summaries', 'source_hash')
    op.drop_column('fiscal_summaries', 'page_ref')
    op.drop_column('fiscal_summaries', 'extraction_id')
    op.drop_constraint('fk_economic_indicators_extraction_id_extractions', 'economic_indicators', type_='foreignkey')
    op.drop_index(op.f('ix_economic_indicators_publishable'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_extraction_id'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_basis'), table_name='economic_indicators')
    op.drop_column('economic_indicators', 'quarantine_reason')
    op.drop_column('economic_indicators', 'publishable')
    op.drop_column('economic_indicators', 'basis')
    op.drop_column('economic_indicators', 'confidence_score')
    op.drop_column('economic_indicators', 'source_hash')
    op.drop_column('economic_indicators', 'page_ref')
    op.drop_column('economic_indicators', 'extraction_id')
    op.drop_constraint('fk_debt_timeline_extraction_id_extractions', 'debt_timeline', type_='foreignkey')
    op.drop_index(op.f('ix_debt_timeline_publishable'), table_name='debt_timeline')
    op.drop_index(op.f('ix_debt_timeline_extraction_id'), table_name='debt_timeline')
    op.drop_index(op.f('ix_debt_timeline_basis'), table_name='debt_timeline')
    op.drop_column('debt_timeline', 'quarantine_reason')
    op.drop_column('debt_timeline', 'publishable')
    op.drop_column('debt_timeline', 'basis')
    op.drop_column('debt_timeline', 'confidence_score')
    op.drop_column('debt_timeline', 'source_hash')
    op.drop_column('debt_timeline', 'page_ref')
    op.drop_column('debt_timeline', 'extraction_id')
    op.drop_constraint('fk_budget_lines_extraction_id_extractions', 'budget_lines', type_='foreignkey')
    op.drop_index(op.f('ix_budget_lines_publishable'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_line_type'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_extraction_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_basis'), table_name='budget_lines')
    op.drop_column('budget_lines', 'quarantine_reason')
    op.drop_column('budget_lines', 'publishable')
    op.drop_column('budget_lines', 'basis')
    _drop_confidence_score_only_if_we_added_it('budget_lines')
    op.drop_column('budget_lines', 'extraction_id')
    op.drop_column('budget_lines', 'line_type')
    op.drop_constraint('fk_audits_extraction_id_extractions', 'audits', type_='foreignkey')
    op.drop_index(op.f('ix_audits_publishable'), table_name='audits')
    op.drop_index(op.f('ix_audits_extraction_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_basis'), table_name='audits')
    op.drop_column('audits', 'quarantine_reason')
    op.drop_column('audits', 'publishable')
    op.drop_column('audits', 'basis')
    _drop_confidence_score_only_if_we_added_it('audits')
    op.drop_column('audits', 'source_hash')
    op.drop_column('audits', 'page_ref')
    op.drop_column('audits', 'extraction_id')
    # ### end Alembic commands ###

    # The type outlives its columns unless dropped explicitly, so a second
    # upgrade would fail with DuplicateObject.
    sa.Enum(name="figurebasis").drop(op.get_bind(), checkfirst=True)
